stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - src/data/data_cleaning.py
      - data/raw/Zomato-Dataset.csv
    outs:
      - data/cleaned/zomato_cleaned.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/cleaned/zomato_cleaned.csv
    outs:
      - data/interim/food_delivery_interim.csv
