stages:

  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - src/data/data_cleaning.py
      - data/raw/Zomato-Dataset.csv
    outs:
      - data/cleaned/zomato_cleaned.csv


  feature_selection:
    cmd: python src/features/feature_selection.py
    deps:
      - src/features/feature_selection.py
      - data/cleaned/zomato_cleaned.csv
    outs:
      - data/interim/food_delivery_interim.csv


  data_splitting:
    cmd: python src/features/data_splitting.py
    deps:
      - src/features/data_splitting.py
      - data/interim/food_delivery_interim.csv
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/test.csv


  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
      - src/features/data_preprocessing.py
      - data/processed/train.csv
    outs:
      - artifacts/preprocessor.pkl


  model_training:
    cmd: python src/models/model_training.py
    deps:
      - src/models/model_training.py
      - data/processed/train.csv
      - artifacts/preprocessor.pkl
      - params.yaml
    outs:
      - models/stacking_cat_rf_pipeline.joblib


  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
      - src/models/model_evaluation.py
      - data/processed/train.csv
      - data/processed/test.csv
      - models/stacking_cat_rf_pipeline.joblib
    metrics:
      - reports/metrics.json:
          cache: false


  model_diagnostics:
    cmd: python src/models/model_diagnostics.py
    deps:
      - src/models/model_diagnostics.py
      - data/processed/test.csv
      - models/stacking_cat_rf_pipeline.joblib
    metrics:
      - reports/diagnostics_metrics.json:
          cache: false
    outs:
      - reports/diagnostics

